# Generated by Django 5.1.6 on 2025-08-04 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_userregister_profile_userregister_firstname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userregister',
            name='Age',
        ),
        migrations.RemoveField(
            model_name='userregister',
            name='Contact',
        ),
        migrations.RemoveField(
            model_name='userregister',
            name='Gender',
        ),
    ]
